### ISSUE TITLE
在Android Studio中按钮中文乱码

### ISSUE THREAD

**Issue by msdx** [FIRHQ/fir_intellig_plugin#51]
Ubuntu下Android Studio的中文容易乱码，我改了字体之后也是一样，能否提供一个英文的界面？

![qq 20150910105224](https://cloud.githubusercontent.com/assets/1903422/9779043/3db5dbde-57aa-11e5-94f0-ae571a347c74.png)

**Comment by yunheli** [comment]
@msdx 我看看哈，之后提供英文界面

**Comment by msdx** [comment]
@yunheli 这个问题可能与你们无关，我的系统被我整出问题来了，依赖混乱，有些系统程序的界面变成英文了。不过还是希望能有个英文菜单，因为ubuntu中android studio对中文的支持不是很好，要改字体才能显示，但会导致在android studio的终端中有输入中文时显示会出现问题。

**Comment by yunheli** [comment]
谢谢 @msdx 的反馈， 会尽快加上英文菜单

**Comment by yunheli** [comment]
@msdx 添加了中英文手动设置  你下载最新版包试试   http://121.201.63.30/Fir_Android_Plugin_2.2.zip

**Comment by msdx** [comment]
试了，帅！
